name: Publish NPM package

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: Install packages
        run: npm i
      - name: Pre-publish
        if: ${{ !secrets.NPM_TOKEN }}
        run: npm run pre-publish
      - name: Publish
        if: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
